name: Auto Deploy to VPS

on:
  push:
    branches:
      - main  # Change to 'staging' or other branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH and pull latest code
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

        ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd /var/www/crm-poin-lp
          git pull origin main
        EOF
